### ISSUE TITLE
page can not render properly

### ISSUE THREAD

**Issue by LywLover** [yyong008/remix-antd-admin#1]
大佬好，刚接触 remix 想学习下，但是本地运行该项目后无法正常渲染页面。
访问页面只要点击任意 sidebar ，sidebar 就会消失，控制台报错 
`Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`
并且不断重复请求 remix.png 和 user.jpg
[截图链接](https://imgur.com/a/rVSjoZV)

BTW: https://remix-antd-admin.vercel.app/ 也无法正常打开

**Comment by yyong008** [comment]
1. 能复你目前电脑的配置吗？
2. 目前正在向 v2 版本升级中
3. 会针对目前已知的问题进行优化（让普通的电脑跑的速度快一点，其他性能问题）
4. 不能访问要自己想办法

**Comment by LywLover** [comment]
1. CPU 13900k
2. vercel 在线版打开没问题了，但本地还是同样问题

**Comment by yyong008** [comment]
关于报错，我这里还没有问题，你反馈的问题和其他问题，会在近期升级 Remix V2 中优化一个版本。

**Comment by yyong008** [comment]
1. 目前已经升级版本到 Remix V2，优化了已知的能解决的问题
2. 目前主要工作偏前端，涉及 remix 的后端 loader/action 等特性
3. 可以学习技术栈，需要跟踪不同型号 cpu 编译 remix 性能问题
4. 欢迎提出宝贵意见
