### ISSUE TITLE
在线地址报错

### ISSUE THREAD

**Issue by djkloop** [yyong008/remix-antd-admin#2]
# 线上
![image](https://github.com/yyong008/remix-antd-admin/assets/21050914/7abf0e30-40d3-4918-b3c5-9ffa12d2f3dc)
# 本地
![image](https://github.com/yyong008/remix-antd-admin/assets/21050914/2b47dc96-1b80-4716-b77c-e191f50d7b28)

**Comment by djkloop** [comment]
# 应该是loading组件里面使用Spin组件的缘故 去掉就好了
![image](https://github.com/yyong008/remix-antd-admin/assets/21050914/22fba0eb-75f5-4018-85c8-6cfa414784a1)

![image](https://github.com/yyong008/remix-antd-admin/assets/21050914/76615a96-1ff0-4c9c-a5d9-b108a50564fe)

**Comment by yyong008** [comment]
> # 应该是loading组件里面使用Spin组件的缘故 去掉就好了
> ![image](https://private-user-images.githubusercontent.com/21050914/303221838-22fba0eb-75f5-4018-85c8-6cfa414784a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzExOTQsIm5iZiI6MTcwNzM3MDg5NCwicGF0aCI6Ii8yMTA1MDkxNC8zMDMyMjE4MzgtMjJmYmEwZWItNzVmNS00MDE4LTg1YzgtNmNmYTQxNDc4NGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA1NDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYTE3NDE0MzlkYzgyNzFlNWM2M2E5MjMxMjU3OWU1ZGZlODFjYjU5NTlhMWE5NjMyMDBjZmE1YzU4MTgxYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2cGxfsO5P_WtkF0tfkbNHWgqAp95EBQ6rz3i6kxRpuU)
> 
> ![image](https://private-user-images.githubusercontent.com/21050914/303221881-76615a96-1ff0-4c9c-a5d9-b108a50564fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzExOTQsIm5iZiI6MTcwNzM3MDg5NCwicGF0aCI6Ii8yMTA1MDkxNC8zMDMyMjE4ODEtNzY2MTVhOTYtMWZmMC00YzljLWE1ZDktYjEwOGE1MDU2NGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA1NDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YzVhNzYyOGI0ZjQzODM4Mzc1N2Q5NWQwMzUyNWUwNjcyOGUxM2I5MmZkZTNmZWM1NjgyYTE3Y2YwZTdjYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcRI5V1SMzyahBWdbnkhzAq6iSetCouG1nZ7xPKeg_4)
排除一下。估计，这个应该是 antd 的 css-in-js 造成。加上 loading 其实就是为了防止水合过程不正确。

**Comment by yyong008** [comment]
> 应该是loading组件里面使用Spin组件的缘故 去掉就好了

Loading 组件已经去掉，感谢反馈

**Comment by yyong008** [comment]
it ok
