### ISSUE TITLE
有考虑支持vite吗？

### ISSUE THREAD

**Issue by luqimin** [yyong008/remix-antd-admin#3]
我自己迁移到vite，感觉和antd有冲突

**Comment by yyong008** [comment]
> 我自己迁移到vite，感觉和antd有冲突

- 考虑到 vite 的构建构建速度，适合本项目，部署问题解决之后会迁移到 vite 过去

**Comment by yyong008** [comment]
> 我自己迁移到vite，感觉和antd有冲突

已完成对 vite 的迁移，有问题可以 issue
