### ISSUE TITLE
关于该项目全栈的疑惑

### ISSUE THREAD

**Issue by Alvazz** [yyong008/remix-antd-admin#6]
作者你好，你这个项目挺不错的。
看到你在Readme里面写到全栈的概念，意思是说，你这个项目分前后端，前端用的是remix，后端用的是啥呢？
我大致看了一下，你后端好像是直接用express写的对吗？
如果说，像我们传统的网站，后端是Go写的，然后提供api给前端，然后前端通过api来获取数据，这种方式，适合remix吗？
还看到你这个项目似乎已经完整实现了rbac了？
非常不错的项目，给你点赞！

**Comment by yyong008** [comment]
全栈可以这样理解：

- Remix、React 渲染前端（CSR, SSR)
- Express 作为 Remix 启动器（可以扩展 Remix 一些能力）
- API 目前没有使用 express，还是 Remix 的 action/loader 的函数（或者装饰器）封装（这里变化大一些）
- rbac 已经实现
- 由于 React 19 原因，项目在关注 Remix 团队的动向。
- 测试架构使用 vitest 单测，使用 cypress 进行 e2e 测试（后期）

remix-antd-admin 是一个开源项目，如果你感兴趣，有时间有能力，可以考虑加入，提供更好的意见支持。感谢认可。

**Comment by yyong008** [comment]
> 作者你好，你这个项目挺不错的。 看到你在Readme里面写到全栈的概念，意思是说，你这个项目分前后端，前端用的是remix，后端用的是啥呢？ 我大致看了一下，你后端好像是直接用express写的对吗？ 如果说，像我们传统的网站，后端是Go写的，然后提供api给前端，然后前端通过api来获取数据，这种方式，适合remix吗？ 还看到你这个项目似乎已经完整实现了rbac了？ 非常不错的项目，给你点赞！

全栈可以这样理解：

Remix、React 渲染前端（CSR, SSR)
Express 作为 Remix 启动器（可以扩展 Remix 一些能力）
API 目前没有使用 express，还是 Remix 的 action/loader 的函数（或者装饰器）封装（这里变化大一些）
rbac 已经实现
由于 React 19 原因，项目在关注 Remix 团队的动向。
测试架构使用 vitest 单测，使用 cypress 进行 e2e 测试（后期）
remix-antd-admin 是一个开源项目，如果你感兴趣，有时间有能力，可以考虑加入，提供更好的意见支持。感谢认可。

**Comment by Alvazz** [comment]
“Express 作为 Remix 启动器（可以扩展 Remix 一些能力）”
-- 这里指的是，用Express来部署 Remix，实际把它跑起来，对吧。（就类似部署在Fly.io的那种形式），只不过有了Express作为Remix的启动器，就可以直接自己在vps上部署Remix了，可以这样理解吧。

"API 目前没有使用 express，还是 Remix 的 action/loader 的函数（或者装饰器）封装（这里变化大一些）"
-- 也就是可以理解为，使用了Remix的action/loader函数，我粗浅的看了下Remix的官方文档，有个BFF的概念，也就是说，通过action/loader方式，可以直接访问https://xxx.com/api这种形式（无关后台是用Java，或者Go，PHP...啥实现的）。

"rbac 已经实现"
-- 全动态的吗？是可以通过后台UI完全动态设置的吗？还是半动态的？

"由于 React 19 原因，项目在关注 Remix 团队的动向。"
-- 展开说说你的担忧？

我非常乐意加入你的这个项目，只不过我本身工作是做C/Rust方面的。主要是做去中心化的一些后端开发。最近有想考虑用Rust写个前端的东西，所以多了解和学习下，目前比较热门的框架能力。

谢谢。
