### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by hanglegehang** [yyong008/remix-antd-admin#7]
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/lihang15/WebstormProjects/remix-antd-admin/node_modules/lodash-es/lodash.js from /Users/lihang15/WebstormProjects/remix-antd-admin/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js not supported.

**Comment by yyong008** [comment]
用 pnpm 试试

**Comment by yyong008** [comment]
> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/lihang15/WebstormProjects/remix-antd-admin/node_modules/lodash-es/lodash.js from /Users/lihang15/WebstormProjects/remix-antd-admin/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js not supported.

Try it with pnpm(用 pnpm 试试)
